name: e2e melange bootstrap + build

on:
  push:
  pull_request:

jobs:
  build:
    name: bootstrap package
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
      options: |
        --cap-add NET_ADMIN --cap-add SYS_ADMIN --security-opt seccomp=unconfined --security-opt apparmor:unconfined

    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      packages: write
      contents: read

    steps:
    - name: Fetch dependencies
      run: |
        cat >/etc/apk/repositories <<_EOF_
        https://dl-cdn.alpinelinux.org/alpine/edge/main
        https://dl-cdn.alpinelinux.org/alpine/edge/community
        https://dl-cdn.alpinelinux.org/alpine/edge/testing
        _EOF_

        apk upgrade -Ua
        apk add go cosign build-base git bubblewrap apko
    - uses: actions/checkout@main
    - name: Build bootstrap melange tool (stage1)
      run: make melange
    - name: Generate a package signing keypair
      run: |
        ./melange keygen
        mv melange.rsa.pub /etc/apk/keys
    - name: Build stage2 melange package with bootstrap melange
      run: ./melange build --pipeline-dir=pipelines/ --signing-key=melange.rsa
    - name: Install stage2 melange package
      run: apk add ./melange-*.apk
    - name: Move stage2 artifacts to stage2 directory
      run: |
        mkdir stage2
        mv melange-*.apk stage2
    - name: Verify operation of stage2 melange
      run: melange version
    - name: Build stage3 melange package with stage2 melange
      run: melange build --signing-key=melange.rsa
    - name: Install stage3 melange package
      run: apk add ./melange-*.apk
    - name: Move stage3 artifacts to stage3 directory
      run: |
        mkdir stage3
        mv melange-*.apk stage3
    - name: Ensure melange package is reproducible
      run: |
        sha256sum stage2/*.apk | sed -e 's:stage2/:stage3/:g' | sha256sum -c
    - name: Verify operation of stage3 melange
      run: melange version
    - name: Prepare local repository
      run: |
        mkdir -p ${GITHUB_WORKSPACE}/repo/$(apk --print-arch)
        mv stage3/melange-*.apk ${GITHUB_WORKSPACE}/repo/$(apk --print-arch)/
        apk index ${GITHUB_WORKSPACE}/repo/$(apk --print-arch)/*.apk --output ${GITHUB_WORKSPACE}/repo/$(apk --print-arch)/APKINDEX.tar.gz
    - name: Sign local repository index
      run: melange sign-index --signing-key=melange.rsa ${GITHUB_WORKSPACE}/repo/$(apk --print-arch)/APKINDEX.tar.gz
    - name: Build melange OCI image with apko
      run: apko publish .apko.yaml ghcr.io/${{ github.repository }}:${{ github.sha }}
